package controller;

import javafx.fxml.FXML;

import javafx.event.ActionEvent;

public class MainController {

	// Event Listener on Button.onAction
	@FXML
	public void btnClick(ActionEvent event) {
		// TODO Autogenerated
	}
}
