package controller;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;
import model.MainModel;

import java.io.IOException;
import java.net.URL;
import java.sql.SQLException;
import java.util.Date;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;

public class MainController implements Initializable {
	public MainModel mainModel = new MainModel();
	@FXML Button btn1;
	
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		btn1.setText("Start");
		
	}
	
	// Event Listener on Button.onAction
	@FXML
	public void btnClick(ActionEvent event) throws SQLException {
		// TODO Autogenerated
		if (btn1.getText() == "Start") {
			mainModel.retrieve();
			try {
				Date date = mainModel.getDateFromFile();
				System.out.println(date);
				mainModel.writeDate(date);
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			btn1.setText("Stop");
		} else {
			btn1.setText("Start");
		}
	}
}
